### ISSUE TITLE
middleware error

### ISSUE THREAD

**Issue by Wormh0-le** [RL-INA/LemgoRL#1]
I got error when i run `python main.py visualize`,
in middleware.py L:314, the returned `internal_cmd` is None，so `curley_braces` will get exception.
Hope your reply soon.

**Comment by vishalrangras** [comment]
@Wormh0-le Thanks for your interest in LemgoRL project and raising an issue for your problem. From the information you shared, it appears that your Lisa+ OmlFgServer is not responding with a valid REST response. The reason for this could be possibly a missing OmlFgServer jar.

Can you please confirm if you have placed the OmlFgServer.jar inside the directory `lisa_vissim_addon/59081`?

If you have correctly placed the jar, can you please share a complete log trace? Also, can you debug and see what is the message you are receiving in put_message_response variable on line 314? Please share the log trace and the data inside put_message_response variable for further debugging of this issue in case OmlFgServer.jar is already present in the above mentioned directory.

**Comment by Wormh0-le** [comment]
Thanks for your reply, I guess it was caused by wrong version of
OmlFgServer.zip
<https://github.com/maxidigital/LisumExamples/blob/master/OmlFgServer.zip>,
now it's work well after i use   OmlFgServer_old.zip
<https://github.com/maxidigital/LisumExamples/blob/master/OmlFgServer_old.zip>
.

Vishal Rangras ***@***.***> 于2021年11月8日周一 下午7:05写道：

**Comment by vishalrangras** [comment]
Closing this issue then since it works with correct version of OmlFgServer.
